/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Control_doctores;
import static Controller.funciones.*;
import Controller.notifyController;
import View.panels.*;
import com.sun.javafx.scene.NodeHelper;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.BorderFactory;
import javax.swing.JLabel;


/**
 *
 * @author DJASC
 */
public class home extends javax.swing.JFrame {
    private int x;
    private int y;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(850, 601);
        setPanel(new p_home());  
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barra_notify = new javax.swing.JPanel();
        btn_min = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        arc_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDoctores = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPacientes = new javax.swing.JLabel();
        lblConfig = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblReservacion = new javax.swing.JLabel();
        lblHorarios = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra_notify.setBackground(new java.awt.Color(50, 60, 75));
        barra_notify.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        barra_notify.setToolTipText("");

        btn_min.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        btn_min.setForeground(new java.awt.Color(102, 102, 102));
        btn_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_min.setText("-");
        btn_min.setToolTipText("");
        btn_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_min.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_minMouseMoved(evt);
            }
        });
        btn_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minMouseExited(evt);
            }
        });

        btn_close.setFont(new java.awt.Font("Berlin Sans FB", 1, 15)); // NOI18N
        btn_close.setForeground(new java.awt.Color(102, 102, 102));
        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setText("X");
        btn_close.setToolTipText("");
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_closeMouseMoved(evt);
            }
        });
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });

        arc_title.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        arc_title.setForeground(new java.awt.Color(255, 255, 255));
        arc_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arc_title.setText("©2016, Arc v.1.0.0.0");

        javax.swing.GroupLayout barra_notifyLayout = new javax.swing.GroupLayout(barra_notify);
        barra_notify.setLayout(barra_notifyLayout);
        barra_notifyLayout.setHorizontalGroup(
            barra_notifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barra_notifyLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(arc_title, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_min, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barra_notifyLayout.setVerticalGroup(
            barra_notifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_notifyLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(barra_notifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barra_notifyLayout.createSequentialGroup()
                        .addGroup(barra_notifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_min, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(barra_notifyLayout.createSequentialGroup()
                        .addComponent(arc_title)
                        .addContainerGap())))
        );

        getContentPane().add(barra_notify, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 42));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/house.png"))); // NOI18N
        jLabel2.setText("  Inicio");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/search.png"))); // NOI18N
        jLabel4.setText("  Busqueda");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/date.png"))); // NOI18N
        jLabel6.setText("  Hoy (Consultas)");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        lblDoctores.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblDoctores.setForeground(new java.awt.Color(102, 102, 102));
        lblDoctores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/doctor.png"))); // NOI18N
        lblDoctores.setText("  Doctores");
        lblDoctores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDoctores.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDoctoresMouseMoved(evt);
            }
        });
        lblDoctores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoctoresMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoctoresMouseExited(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        lblPacientes.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblPacientes.setForeground(new java.awt.Color(102, 102, 102));
        lblPacientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/user.png"))); // NOI18N
        lblPacientes.setText("  Pacientes");
        lblPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPacientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblPacientesMouseMoved(evt);
            }
        });
        lblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPacientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPacientesMouseExited(evt);
            }
        });

        lblConfig.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblConfig.setForeground(new java.awt.Color(102, 102, 102));
        lblConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/settings.png"))); // NOI18N
        lblConfig.setText(" Configuracion");
        lblConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfig.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblConfigMouseMoved(evt);
            }
        });
        lblConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfigMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfigMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Ayuda");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/help.png"))); // NOI18N

        Separator.setForeground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/file.png"))); // NOI18N
        jLabel16.setText("  Historial Clinico");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel16MouseMoved(evt);
            }
        });
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/volume.png"))); // NOI18N
        jLabel17.setText(" Notificaciones");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel17MouseMoved(evt);
            }
        });
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });

        lblReservacion.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblReservacion.setForeground(new java.awt.Color(102, 102, 102));
        lblReservacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblReservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/post.png"))); // NOI18N
        lblReservacion.setText("  Reservaciones");
        lblReservacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReservacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblReservacionMouseMoved(evt);
            }
        });
        lblReservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReservacionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReservacionMouseExited(evt);
            }
        });

        lblHorarios.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblHorarios.setForeground(new java.awt.Color(102, 102, 102));
        lblHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/menu/dateTime.png"))); // NOI18N
        lblHorarios.setText(" Horarios");
        lblHorarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHorarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblHorariosMouseMoved(evt);
            }
        });
        lblHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHorariosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHorariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDoctores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Separator)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHorarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 200, 558));

        escritorio.setBackground(new java.awt.Color(253, 253, 253));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 42, 650, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_minMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseMoved
        hoverClose(btn_min);
    }//GEN-LAST:event_btn_minMouseMoved

    private void btn_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseClicked
        // TODO add your handling code here:
        setExtendedState(login.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_btn_minMouseClicked

    private void btn_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseExited
        // TODO add your handling code here:
        outClose(btn_min);
    }//GEN-LAST:event_btn_minMouseExited

    private void btn_closeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseMoved
        // TODO add your handling code here:
        hoverClose(btn_close);
    }//GEN-LAST:event_btn_closeMouseMoved

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        // TODO add your handling code here:
        outClose(btn_close);
    }//GEN-LAST:event_btn_closeMouseExited

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
          setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
         x = evt.getX();
          y = evt.getY();
    }//GEN-LAST:event_formMousePressed
    private void menuMoved(JLabel j){
        j.setOpaque(true);
        j.setBackground(new Color(50,60,75));
        j.setForeground(Color.white);
        j.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        
    }
    private void menuOut(JLabel j){
        j.setOpaque(false);
        j.setForeground(new Color(102,102,102));
        j.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
    }
    
    private void lblDoctoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctoresMouseExited
        // TODO add your handling code here:
        menuOut(lblDoctores);
    }//GEN-LAST:event_lblDoctoresMouseExited

    private void lblDoctoresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctoresMouseMoved
        // TODO add your handling code here:
        menuMoved(lblDoctores);
     
    }//GEN-LAST:event_lblDoctoresMouseMoved

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
          menuOut(jLabel2);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        // TODO add your handling code here:
         menuMoved(jLabel2);
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        menuMoved(jLabel4);
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        menuOut(jLabel4);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        menuOut(jLabel6);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
       menuMoved(jLabel6);
    }//GEN-LAST:event_jLabel6MouseMoved

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        menuOut(jLabel16);
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel16MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseMoved
        menuMoved(jLabel16);
    }//GEN-LAST:event_jLabel16MouseMoved

    private void lblPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPacientesMouseExited
         menuOut(lblPacientes);
    }//GEN-LAST:event_lblPacientesMouseExited

    private void lblPacientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPacientesMouseMoved
        menuMoved(lblPacientes);
    }//GEN-LAST:event_lblPacientesMouseMoved

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        setPanel(new p_home());
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        setPanel(new p_search());
        View.panels.p_search.view ="";
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        setPanel(new p_today());
    }//GEN-LAST:event_jLabel6MouseClicked

    private void lblDoctoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctoresMouseClicked
        // TODO add your handling code here:
        setPanel(new p_doctor());
    }//GEN-LAST:event_lblDoctoresMouseClicked

    private void lblReservacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReservacionMouseMoved
        menuMoved(lblReservacion);
    }//GEN-LAST:event_lblReservacionMouseMoved

    private void lblReservacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReservacionMouseExited
        menuOut(lblReservacion);
    }//GEN-LAST:event_lblReservacionMouseExited

    private void lblReservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReservacionMouseClicked
        // TODO add your handling code here:
        setPanel(new p_reserv());
        
    }//GEN-LAST:event_lblReservacionMouseClicked

    private void lblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPacientesMouseClicked
        setPanel(new p_paciente());
    }//GEN-LAST:event_lblPacientesMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        setPanel(new p_history());
    }//GEN-LAST:event_jLabel16MouseClicked

    private void lblConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigMouseClicked
       setPanel(new p_config());
    }//GEN-LAST:event_lblConfigMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
       setPanel(new p_notify());
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel17MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseMoved
        menuMoved(jLabel17);
    }//GEN-LAST:event_jLabel17MouseMoved

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        menuOut(jLabel17);
    }//GEN-LAST:event_jLabel17MouseExited

    private void lblHorariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHorariosMouseMoved
        menuMoved(lblHorarios);
    }//GEN-LAST:event_lblHorariosMouseMoved

    private void lblHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHorariosMouseClicked
        setPanel(new p_horarios());
    }//GEN-LAST:event_lblHorariosMouseClicked

    private void lblHorariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHorariosMouseExited
          menuOut(lblHorarios);
    }//GEN-LAST:event_lblHorariosMouseExited

    private void lblConfigMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigMouseMoved
        menuMoved(lblConfig);
    }//GEN-LAST:event_lblConfigMouseMoved

    private void lblConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigMouseExited
        menuOut(lblConfig);
    }//GEN-LAST:event_lblConfigMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JSeparator Separator;
    public static javax.swing.JLabel arc_title;
    public static javax.swing.JPanel barra_notify;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_min;
    public static javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblConfig;
    public javax.swing.JLabel lblDoctores;
    public javax.swing.JLabel lblHorarios;
    public javax.swing.JLabel lblPacientes;
    public javax.swing.JLabel lblReservacion;
    // End of variables declaration//GEN-END:variables
}
