/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.panels;

import Controller.Control_horarios;
import Controller.notifyController;
import com.sun.glass.events.KeyEvent;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Daniel
 */
public class p_horarios extends javax.swing.JPanel {

    /**
     * Creates new form p_horarios
     */
    JFormattedTextField txt;
    Control_horarios ch;
    public p_horarios() {
        initComponents();
        ch = new Control_horarios();
//        p_search.tbResult.setDefaultRenderer(String.class, renderer);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        H_menu = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        h_Submdelete = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        Panel_Horario = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        h_btn_searh_doc = new javax.swing.JButton();
        h_dr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        h_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        h_slideHora = new javax.swing.JSlider();
        h_slide_min = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        h_btnGuardar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        h_txtHoraIni = new javax.swing.JFormattedTextField();
        h_txthoraFin = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        h_txtDuracion = new javax.swing.JFormattedTextField();
        h_btnActualizar = new javax.swing.JButton();
        h_Busqueda_horario = new javax.swing.JTextField();
        panel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        h_tbHorario = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        h_txtbusqueda = new javax.swing.JTextField();

        jMenuItem1.setText("Activar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        H_menu.add(jMenuItem1);

        h_Submdelete.setText("Dar de baja");
        h_Submdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h_SubmdeleteActionPerformed(evt);
            }
        });
        H_menu.add(h_Submdelete);

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/calendar.png"))); // NOI18N
        jLabel1.setText("  Horarios ");

        lblMensaje.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(111, 111, 111));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("Buscar doctor por cedula o nombre");

        Panel_Horario.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Busqueda: ");

        h_btn_searh_doc.setText("BUSCAR");

        h_dr.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Hora Inicio: ");

        h_id.setEditable(false);
        h_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Dr. (a): ");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Hora Fin: ");

        h_slideHora.setBackground(new java.awt.Color(255, 255, 255));
        h_slideHora.setMaximum(23);
        h_slideHora.setMinorTickSpacing(1);
        h_slideHora.setValue(0);
        h_slideHora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        h_slideHora.setEnabled(false);
        h_slideHora.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                h_slideHoraStateChanged(evt);
            }
        });

        h_slide_min.setBackground(new java.awt.Color(255, 255, 255));
        h_slide_min.setMaximum(59);
        h_slide_min.setToolTipText("");
        h_slide_min.setValue(0);
        h_slide_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        h_slide_min.setEnabled(false);
        h_slide_min.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                h_slide_minStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Horas: ");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Minutos: ");

        h_btnGuardar.setText("GUARDAR");
        h_btnGuardar.setEnabled(false);
        h_btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h_btnGuardarActionPerformed(evt);
            }
        });

        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        h_txtHoraIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        h_txtHoraIni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        h_txtHoraIni.setText("8:00:00");
        h_txtHoraIni.setEnabled(false);
        h_txtHoraIni.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        h_txtHoraIni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                h_txtHoraIniFocusGained(evt);
            }
        });

        h_txthoraFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        h_txthoraFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        h_txthoraFin.setText("16:30:00");
        h_txthoraFin.setEnabled(false);
        h_txthoraFin.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        h_txthoraFin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                h_txthoraFinFocusGained(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Duracion: ");

        h_txtDuracion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        h_txtDuracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        h_txtDuracion.setText("00:30:00");
        h_txtDuracion.setEnabled(false);
        h_txtDuracion.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        h_txtDuracion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                h_txtDuracionFocusGained(evt);
            }
        });

        h_btnActualizar.setText("ACTUALIZAR");
        h_btnActualizar.setEnabled(false);
        h_btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h_btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(h_slideHora, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(h_txtHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h_txthoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h_txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(h_dr, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                    .addComponent(h_Busqueda_horario))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h_btn_searh_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h_id, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(h_slide_min, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(h_btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(h_btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_btn_searh_doc, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(h_Busqueda_horario))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(h_dr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_id, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_txtHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_txthoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(h_slideHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(h_slide_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h_btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h_btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        Panel_Horario.addTab("Configurar", jPanel1);

        panel2.setBackground(new java.awt.Color(255, 255, 255));

        h_tbHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        h_tbHorario.setComponentPopupMenu(H_menu);
        h_tbHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                h_tbHorarioMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(h_tbHorario);

        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(h_txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(84, 84, 84)))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(h_txtbusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        Panel_Horario.addTab("Modificar", panel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Panel_Horario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Horario))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void h_slideHoraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_h_slideHoraStateChanged
        if(txt !=null){
            String []h =txt.getText().split(":");
            int val = h_slideHora.getValue();
            txt.setText(val+":"+h[1]+":00");
        }
    }//GEN-LAST:event_h_slideHoraStateChanged

    private void h_txtHoraIniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_h_txtHoraIniFocusGained
       txt = h_txtHoraIni;
       String []h =h_txtHoraIni.getText().split(":");
       h_slideHora.setValue(Integer.parseInt(h[0]));
       h_slide_min.setValue(Integer.parseInt(h[1]));
    }//GEN-LAST:event_h_txtHoraIniFocusGained

    private void h_txthoraFinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_h_txthoraFinFocusGained
        txt = h_txthoraFin;
        String []h =h_txthoraFin.getText().split(":");
        h_slideHora.setValue(Integer.parseInt(h[0]));
        h_slide_min.setValue(Integer.parseInt(h[1]));
    }//GEN-LAST:event_h_txthoraFinFocusGained

    private void h_slide_minStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_h_slide_minStateChanged
       if(txt!=null){
        String []time = txt.getText().split(":");
        int val = h_slide_min.getValue();
        if(val>9){
        txt.setText(time[0]+":"+val+":00");}
        else{
         txt.setText(time[0]+":0"+val+":00");
        }
       } 
    }//GEN-LAST:event_h_slide_minStateChanged

    private void h_txtbusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_h_txtbusquedaFocusLost
       String ced = h_Busqueda_horario.getText();
       if(!ced.equals(""))
       {
           String []notify = ch.validar_horario(ced).split(";");
           if(notify.length==2){
           notifyController.setNotify(notify[1], notify[0]);}
       }
    }//GEN-LAST:event_h_txtbusquedaFocusLost

    private void h_btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h_btnGuardarActionPerformed
        int id_doc =(h_id.getText().equals(""))?0:Integer.parseInt(h_id.getText());
        String hora_in = h_txtHoraIni.getText();
        String hora_out = h_txthoraFin.getText();
        String duracion = h_txtDuracion.getText();
        if(id_doc>0){
        String []notify = ch.validar_datos(id_doc,hora_in,hora_out,duracion,1).split(";");
        notifyController.setNotify(notify[1], notify[0]);}
    }//GEN-LAST:event_h_btnGuardarActionPerformed

    private void h_txtDuracionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_h_txtDuracionFocusGained
        txt = h_txtDuracion;
       String []h =txt.getText().split(":");
       h_slideHora.setValue(Integer.parseInt(h[0]));
       h_slide_min.setValue(Integer.parseInt(h[1]));
    }//GEN-LAST:event_h_txtDuracionFocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String cedula = h_Busqueda_horario.getText();
        ch.cargar_horarios(cedula);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void h_tbHorarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h_tbHorarioMousePressed
       if(evt.getClickCount()==2){
          int row = h_tbHorario.getSelectedRow();
            if(row>=0){
                 ch.cargarDatos_edicion(row);
            } 
       }
    }//GEN-LAST:event_h_tbHorarioMousePressed

    private void h_btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h_btnActualizarActionPerformed
        int id_doc =(h_id.getText().equals(""))?0:Integer.parseInt(h_id.getText());
        if(id_doc!=0){
        String hora_in = h_txtHoraIni.getText();
        String hora_out = h_txthoraFin.getText();
        String duracion = h_txtDuracion.getText();
        String []notify = ch.validar_datos(id_doc,hora_in,hora_out,duracion,2).split(";");
        notifyController.setNotify(notify[1], notify[0]);
        
        }else{
            notifyController.setNotify("Debes seleccionar un doctor :D", "Alert");
        }
    }//GEN-LAST:event_h_btnActualizarActionPerformed

    private void h_SubmdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h_SubmdeleteActionPerformed
        int row = h_tbHorario.getSelectedRow();
        if(row>=0){
            String []notify = ch.active_and_desactive_horario(row,"0").split(";");
            notifyController.setNotify(notify[1], notify[0]);
        }
    }//GEN-LAST:event_h_SubmdeleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ch.limpiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int row = h_tbHorario.getSelectedRow();
        if(row>=0){
            String []notify =ch.active_and_desactive_horario(row,"1").split(";");
            notifyController.setNotify(notify[1], notify[0]);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void h_txtbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_h_txtbusquedaKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
       String ced = h_Busqueda_horario.getText();
       if(!ced.equals(""))
       {
           String []notify = ch.validar_horario(ced).split(";");
           notifyController.setNotify(notify[1], notify[0]);
       }
       }
    }//GEN-LAST:event_h_txtbusquedaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu H_menu;
    public static javax.swing.JTabbedPane Panel_Horario;
    public static javax.swing.JTextField h_Busqueda_horario;
    private javax.swing.JMenuItem h_Submdelete;
    public static javax.swing.JButton h_btnActualizar;
    public static javax.swing.JButton h_btnGuardar;
    private javax.swing.JButton h_btn_searh_doc;
    public static javax.swing.JTextField h_dr;
    public static javax.swing.JTextField h_id;
    public static javax.swing.JSlider h_slideHora;
    public static javax.swing.JSlider h_slide_min;
    public static javax.swing.JTable h_tbHorario;
    public static javax.swing.JFormattedTextField h_txtDuracion;
    public static javax.swing.JFormattedTextField h_txtHoraIni;
    public static javax.swing.JTextField h_txtbusqueda;
    public static javax.swing.JFormattedTextField h_txthoraFin;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
