/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.panels;

import Controller.Control_busqueda;


/**
 *
 * @author Youtteam
 */
public class p_search extends javax.swing.JPanel {

    /**
     * Creates new form index
     */
    Control_busqueda  control;
    public static String view="";
    public p_search() {
        initComponents();
        control = new Control_busqueda();
    }
    public static void initSearch(){
        if(view.equals("")){
            
        }
        else if(view.equals("doc"))
        {
            rdPacientes.setEnabled(false);
            rdCitas.setEnabled(false);
            rdPrecios.setEnabled(false);
            rdDoctores.setSelected(true);
        }
        else if(view.equals("pac"))
        {
            rdPacientes.setEnabled(true);
            rdCitas.setEnabled(false);
            rdPrecios.setEnabled(false);
            rdDoctores.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResult = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rdPacientes = new javax.swing.JRadioButton();
        rdDoctores = new javax.swing.JRadioButton();
        rdCitas = new javax.swing.JRadioButton();
        rdPrecios = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(253, 253, 253));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tbResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbResultMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbResult);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/search.png"))); // NOI18N
        jLabel1.setText("Buscar");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(111, 111, 111));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Realize Una Busqueda, en Nuestro Buscador Inteligente");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Iniciar Busqueda");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rdPacientes.setBackground(new java.awt.Color(253, 253, 253));
        grupo1.add(rdPacientes);
        rdPacientes.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdPacientes.setForeground(new java.awt.Color(91, 91, 91));
        rdPacientes.setSelected(true);
        rdPacientes.setText("Pacientes");
        rdPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        rdDoctores.setBackground(new java.awt.Color(253, 253, 253));
        grupo1.add(rdDoctores);
        rdDoctores.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdDoctores.setForeground(new java.awt.Color(91, 91, 91));
        rdDoctores.setText("Doctores");
        rdDoctores.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        rdCitas.setBackground(new java.awt.Color(253, 253, 253));
        grupo1.add(rdCitas);
        rdCitas.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdCitas.setForeground(new java.awt.Color(91, 91, 91));
        rdCitas.setText("Citas Medicas");
        rdCitas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        rdPrecios.setBackground(new java.awt.Color(253, 253, 253));
        grupo1.add(rdPrecios);
        rdPrecios.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdPrecios.setForeground(new java.awt.Color(91, 91, 91));
        rdPrecios.setText("Precios Consulta");
        rdPrecios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdPacientes)
                                        .addGap(10, 10, 10)
                                        .addComponent(rdDoctores)
                                        .addGap(10, 10, 10)
                                        .addComponent(rdCitas)
                                        .addGap(10, 10, 10)
                                        .addComponent(rdPrecios))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1))))
                        .addGap(0, 61, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdPacientes)
                    .addComponent(rdDoctores)
                    .addComponent(rdCitas)
                    .addComponent(rdPrecios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbResultMousePressed
       
        if(evt.getClickCount()==2){
            if(view.equals("doc"))
            {
                control.llenar_campos(tbResult.getSelectedRow());
            }
            if(view.equals("pac"))
            {
                control.llenar_campos(tbResult.getSelectedRow());
            }
        }
        
    }//GEN-LAST:event_tbResultMousePressed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
       control.mostarDatos();
    }//GEN-LAST:event_txtSearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JRadioButton rdCitas;
    public static javax.swing.JRadioButton rdDoctores;
    public static javax.swing.JRadioButton rdPacientes;
    public static javax.swing.JRadioButton rdPrecios;
    public static javax.swing.JTable tbResult;
    public static javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
