/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.panels;

import Controller.Control_filtrado;

/**
 *
 * @author LAB5-PC17
 */
public class p_today extends javax.swing.JPanel {

    /**
     * Creates new form index
     */
    Control_filtrado cf;
    public p_today() {
        initComponents();
        cf = new Control_filtrado();
        cf.filtro_by_horarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_rdHorarios = new javax.swing.JRadioButton();
        t_rdDoctores = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_tbFiltrado = new javax.swing.JTable();
        t_rdPacientes = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(253, 253, 253));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/calendar.png"))); // NOI18N
        jLabel1.setText("Reservaciones");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(111, 111, 111));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Estas son las consultas que se deben atender Hoy.");

        t_rdHorarios.setBackground(new java.awt.Color(253, 253, 253));
        grupo1.add(t_rdHorarios);
        t_rdHorarios.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        t_rdHorarios.setForeground(new java.awt.Color(91, 91, 91));
        t_rdHorarios.setSelected(true);
        t_rdHorarios.setText("Filtrar por Horarios");
        t_rdHorarios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        t_rdHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_rdHorariosActionPerformed(evt);
            }
        });

        t_rdDoctores.setBackground(new java.awt.Color(253, 253, 253));
        grupo1.add(t_rdDoctores);
        t_rdDoctores.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        t_rdDoctores.setForeground(new java.awt.Color(91, 91, 91));
        t_rdDoctores.setText("Filtrar por Doctores");
        t_rdDoctores.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        t_rdDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_rdDoctoresActionPerformed(evt);
            }
        });

        t_tbFiltrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha/Hora", "Doctor/Consultorio", "Paciente", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t_tbFiltrado);

        t_rdPacientes.setBackground(new java.awt.Color(253, 253, 253));
        grupo1.add(t_rdPacientes);
        t_rdPacientes.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        t_rdPacientes.setForeground(new java.awt.Color(91, 91, 91));
        t_rdPacientes.setText("Filtrar por Pacientes");
        t_rdPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        t_rdPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_rdPacientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t_rdHorarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_rdDoctores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_rdPacientes)))
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_rdHorarios)
                    .addComponent(t_rdDoctores)
                    .addComponent(t_rdPacientes))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_rdDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_rdDoctoresActionPerformed
        cf.filtro_by_doctor();
    }//GEN-LAST:event_t_rdDoctoresActionPerformed

    private void t_rdHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_rdHorariosActionPerformed
        cf.filtro_by_horarios();
    }//GEN-LAST:event_t_rdHorariosActionPerformed

    private void t_rdPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_rdPacientesActionPerformed
        cf.filtro_by_paciente();
    }//GEN-LAST:event_t_rdPacientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JRadioButton t_rdDoctores;
    public static javax.swing.JRadioButton t_rdHorarios;
    private javax.swing.JRadioButton t_rdPacientes;
    public static javax.swing.JTable t_tbFiltrado;
    // End of variables declaration//GEN-END:variables
}
